CREATE TABLE produtos (
	id SERIAL NOT NULL PRIMARY KEY,
	nome VARCHAR (50) NOT NULL,
	preco REAL NOT NULL
)

CREATE TABLE usuarios (
	id SERIAL NOT NULL PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	username VARCHAR(20) NOT NULL,
	senha VARCHAR(20) NOT NULL
)